spring:
  application:
    name: eureka-server
  profiles:
    active: eureka1

server:
  port: 2001

eureka:
  server:
    #    eureka 的自我保护状态：心跳失败的比例，在15分钟内是否超过85%,如果出现了低于的情况，
    #    Eureka Server会将当前的实例注册信息保护起来，同时提示一个警告，一旦进入保护模式，
    #    Eureka Server将会尝试保护其服务注册表中的信息，不再删除服务注册表中的数据。也就是不会注销任何微服务
    enable-self-preservation: false
  instance:
    #    eureka 集群服务器之间，通过 hostname 来区分
    hostname: eureka1
    #    最后一次心跳后，间隔多久认定微服务不可用，默认90
    lease-expiration-duration-in-seconds: 90
  client:
    #    不向自身注册
    register-with-eureka: false
    #    不从自身拉取注册信息
    fetch-registry: false